### ISSUE TITLE
Error: Could not resolve './fi/hg/core/RequestServer'

### ISSUE THREAD

**Issue by thejhh** [hangovergames/create-backend#2]
```
[!] Error: Could not resolve './fi/hg/core/RequestServer' from src/main.ts
Error: Could not resolve './fi/hg/core/RequestServer' from src/main.ts
    at error (/Users/jhh/tmp/foo-backend/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.handleResolveId (/Users/jhh/tmp/foo-backend/node_modules/rollup/dist/shared/rollup.js:22287:24)
    at /Users/jhh/tmp/foo-backend/node_modules/rollup/dist/shared/rollup.js:22250:26
```

**Comment by thejhh** [comment]
Root cause for this problem is that we've moved some node specific code to `fi.hg.node` . I will add it there and fix imports.
